# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Block_correctionV2/Block_correctionV2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_correctionV2 || ORIG_REF_NAME==Block_correctionV2} -quiet] -quiet

# IP: bd/Block_correctionV2/ip/Block_correctionV2_Adder_0_0/Block_correctionV2_Adder_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_correctionV2_Adder_0_0 || ORIG_REF_NAME==Block_correctionV2_Adder_0_0} -quiet] -quiet

# IP: bd/Block_correctionV2/ip/Block_correctionV2_ControllerV2_0_0/Block_correctionV2_ControllerV2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_correctionV2_ControllerV2_0_0 || ORIG_REF_NAME==Block_correctionV2_ControllerV2_0_0} -quiet] -quiet

# IP: bd/Block_correctionV2/ip/Block_correctionV2_find_error_0_0/Block_correctionV2_find_error_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_correctionV2_find_error_0_0 || ORIG_REF_NAME==Block_correctionV2_find_error_0_0} -quiet] -quiet

# IP: bd/Block_correctionV2/ip/Block_correctionV2_correct_error_0_0/Block_correctionV2_correct_error_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_correctionV2_correct_error_0_0 || ORIG_REF_NAME==Block_correctionV2_correct_error_0_0} -quiet] -quiet

# IP: bd/Block_correctionV2/ip/Block_correctionV2_calc_parity_0_0/Block_correctionV2_calc_parity_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_correctionV2_calc_parity_0_0 || ORIG_REF_NAME==Block_correctionV2_calc_parity_0_0} -quiet] -quiet

# IP: bd/Block_correctionV2/ip/Block_correctionV2_Output_memmory_0_0/Block_correctionV2_Output_memmory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_correctionV2_Output_memmory_0_0 || ORIG_REF_NAME==Block_correctionV2_Output_memmory_0_0} -quiet] -quiet

# IP: bd/Block_correctionV2/ip/Block_correctionV2_Input_memmory_0_0/Block_correctionV2_Input_memmory_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Block_correctionV2_Input_memmory_0_0 || ORIG_REF_NAME==Block_correctionV2_Input_memmory_0_0} -quiet] -quiet

# XDC: c:/Users/daanv/Desktop/MO8/Demodulator/Demodulator.gen/sources_1/bd/Block_correctionV2/Block_correctionV2_ooc.xdc
